services:
  uptime-kuma:
    image: uptime-kuma:latest
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    restart: unless-stopped
    container_name: uptime-kuma
    networks:
      - anpr_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    container_name: mysql
    networks:
      - anpr_network
    environment:
      MYSQL_ROOT_PASSWORD: A1Rook1es@123
      MYSQL_DATABASE: uptimekuma
      MYSQL_USER: uptimekuma
      MYSQL_PASSWORD: AiRook1es@123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  anpr_network:
    external: true

