apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuma-pvc
  namespace: admin-tools
spec:
  resources:
    requests:
      storage: 8G
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
