apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuma
  labels:
    app: kuma
spec:

  replicas: 1
  selector:
    matchLabels:
      app: kuma
  template:
    metadata:
      labels:
        app: kuma
    spec:
      volumes:
        - name: kuma-vol
          persistentVolumeClaim:
            claimName: kuma-pv-claim
      containers:
      - name: kuma
        image: docker.io/louislam/uptime-kuma:1.18.3
        ports:
        - containerPort: 3001
        volumeMounts:
          - mountPath: /app/data
            name: kuma-vol
