apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuma-pv-claim
spec:
  storageClassName: premium-rwo # use your Storage ClassName
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
