apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "uk.fullname" . }}
  labels:
    {{- include "uk.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi