apiVersion: v1
kind: Service
metadata:
  name: {{ include "uk.fullname" . }}
  labels:
    {{- include "uk.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ws
      protocol: TCP
      name: app
  selector:
    {{- include "uk.selectorLabels" . | nindent 4 }}
