name: Auto Fix Lint Issues

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          # Enable your linters here
          eslint: true
          auto_fix: true
